#! /usr/bin/env python3

"""
------------------------------------------------------------------------

NOME
    test_survey.py - Testando a classe AnonymousSurvey.

------------------------------------------------------------------------

SINOPSES
    from survey import AnonymousSurvey

------------------------------------------------------------------------

DESCRIÇÃO
    - Testando a classe AnonymousSurvey:


------------------------------------------------------------------------

HISTÓRICO
    20202911: João Paulo, novembro de 2020.
        - Testando a classe AnonymousSurvey (pg 267-268).

------------------------------------------------------------------------

"""


import unittest
from survey import AnonymousSurvey


class TestAnonymousSurvey(unittest.TestCase):
    """Testes para a classe AnonymousSurvey."""


    def test_store_single_response(self):
        """Testa se uma única resposta é armazenada de forma
        apropriada."""
        question = "What language did you first learn to speak? "
        my_survey = AnonymousSurvey(question)
        my_survey.store_response('English')
        self.assertIn('English', my_survey.responses)


unittest.main()
